WINDOW_WIDTH = 900
WINDOW_HEIGHT = 800
BOIDS_NUMBER = 50

MAX_ANGLE = 180
BOID_PERCEPTION_DISTANCE = 70
BOID_COHESION_FACTOR = 1
BOID_ALIGNMENT_FACTOR = 1
BOID_SEPARATION_FACTOR = 1
BOID_MAX_SPEED = 5
BORDER_WIDTH = 40
BORDER_REPEL_FACTOR = 0.5
